name: van_flow
description: "A Decision Support System for Driver Application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  get_it: ^8.0.3
  flutter_background_service: ^5.0.10
  path_provider: ^2.1.5
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_notification_listener: ^1.3.4
  flutter_overlay_window: ^0.5.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: 3.1.0+1
  build_runner: 2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/data/districts.json
    - assets/data/diaphanhuyen.geojson
